
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione4;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int CHAR_CONST = 52;
  public static final int POW = 37;
  public static final int CHAR = 10;
  public static final int GE = 45;
  public static final int INTEGER_CONST = 51;
  public static final int SEMI = 3;
  public static final int INT = 7;
  public static final int OUT = 16;
  public static final int RBRAC = 30;
  public static final int FOR = 17;
  public static final int MINUS = 34;
  public static final int WRITE = 25;
  public static final int NOT = 41;
  public static final int AND = 39;
  public static final int LT = 42;
  public static final int RPAR = 28;
  public static final int OR = 40;
  public static final int BOOL = 11;
  public static final int COMMA = 4;
  public static final int DIV = 36;
  public static final int LOOP = 23;
  public static final int PLUS = 33;
  public static final int ASSIGN = 46;
  public static final int MAIN = 2;
  public static final int IF = 18;
  public static final int WRITELN = 26;
  public static final int ID = 49;
  public static final int LE = 43;
  public static final int EOF = 0;
  public static final int RETURN = 32;
  public static final int TRUE = 13;
  public static final int error = 1;
  public static final int PIPE = 5;
  public static final int VOID = 12;
  public static final int EQ = 47;
  public static final int REAL = 8;
  public static final int TIMES = 35;
  public static final int COLON = 31;
  public static final int ELSE = 20;
  public static final int READ = 24;
  public static final int TO = 22;
  public static final int WHILE = 21;
  public static final int STR_CONCAT = 38;
  public static final int REAL_CONST = 50;
  public static final int THEN = 19;
  public static final int NE = 48;
  public static final int LPAR = 27;
  public static final int STRING = 9;
  public static final int DEF = 15;
  public static final int LBRAC = 29;
  public static final int FALSE = 14;
  public static final int STRING_CONST = 53;
  public static final int GT = 44;
  public static final int VAR = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "SEMI",
  "COMMA",
  "PIPE",
  "VAR",
  "INT",
  "REAL",
  "STRING",
  "CHAR",
  "BOOL",
  "VOID",
  "TRUE",
  "FALSE",
  "DEF",
  "OUT",
  "FOR",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "TO",
  "LOOP",
  "READ",
  "WRITE",
  "WRITELN",
  "LPAR",
  "RPAR",
  "LBRAC",
  "RBRAC",
  "COLON",
  "RETURN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "STR_CONCAT",
  "AND",
  "OR",
  "NOT",
  "LT",
  "LE",
  "GT",
  "GE",
  "ASSIGN",
  "EQ",
  "NE",
  "ID",
  "REAL_CONST",
  "INTEGER_CONST",
  "CHAR_CONST",
  "STRING_CONST"
  };
}

